# -*- coding: utf-8 -*-
"""day_12(ml)_mean_shift_clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c25ixrFZAlW7Y2qTaQyyhj27mHUtWD51
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401
from sklearn.cluster import MeanShift, estimate_bandwidth
from sklearn.datasets import make_blobs

coordinates = [
    [1, 1, 1],
    [5, 5, 5],
    [10, 10, 10]
]

X, _ = make_blobs(
    n_samples=150,
    centers=coordinates,
    cluster_std=0.6,
    random_state=42
)

fig_raw = plt.figure(figsize=(10, 8))
ax_raw = fig_raw.add_subplot(111, projection="3d")
ax_raw.scatter(X[:, 0], X[:, 1], X[:, 2], marker="o", c="#7f3fbf")
ax_raw.set_title("Raw 3D data")
plt.show()

bandwidth = estimate_bandwidth(X, quantile=0.2, n_samples=500)

ms = MeanShift(bandwidth=bandwidth, bin_seeding=True)
ms.fit(X)

cluster_centers = ms.cluster_centers_
labels = ms.labels_
cluster_labels = np.unique(labels)
n_clusters = len(cluster_labels)
print("Number of clusters:", n_clusters)

fig_ms = plt.figure(figsize=(10, 8))
ax_ms = fig_ms.add_subplot(111, projection="3d")
for k in cluster_labels:
    cluster_members = labels == k
    ax_ms.scatter(
        X[cluster_members, 0],
        X[cluster_members, 1],
        X[cluster_members, 2],
        marker="o",
        s=40,
        label=f"Cluster {k}"
    )

ax_ms.scatter(
    cluster_centers[:, 0],
    cluster_centers[:, 1],
    cluster_centers[:, 2],
    marker="x",
    c="green",
    s=300,
    linewidths=2,
    zorder=10
)

ax_ms.set_title(f"Mean Shift Clustering (estimated clusters = {n_clusters})")
ax_ms.legend()
plt.show()